import Anthropic from '@anthropic-ai/sdk';
import { queryMemories, getMemoryStats, analyzeConnections, type Memory } from './engine';
import { calculateIQScore, type IQScore } from './iqScore';

const client = new Anthropic();

// ============================================================
// Memory Intelligence Report
// Generated by Donna every morning per tenant
// ============================================================

export interface MemoryReport {
  reportDate: string;
  tenantId: string;
  generatedBy: string;

  // Sections
  newMemories: { id: string; content: string; type: string }[];
  connectionsMade: { from: string; to: string; relationship: string }[];
  flaggedReview: { id: string; content: string; reason: string }[];

  // Health stats
  stats: {
    totalMemories: number;
    confidenceAvg: number;
    connectionCount: number;
    predictiveTriggers: number;
    byType: Record<string, number>;
  };

  // IQ Score
  iqScore: IQScore;

  // AI-generated summary
  summary: string;
}

export async function generateDailyReport(tenantId: string): Promise<MemoryReport> {
  const stats = getMemoryStats(tenantId);
  const iqScore = calculateIQScore(tenantId);

  // Get recent memories (last 24 hours simulated)
  const allMemories = queryMemories({ tenantId, limit: 50 });
  const recent = allMemories.slice(0, 10); // most recent

  // New memories
  const newMemories = recent.map(m => ({
    id: m.id,
    content: m.content,
    type: m.type,
  }));

  // Discover connections
  const newConnections = await analyzeConnections(tenantId);
  const connectionsMade = newConnections.map(c => {
    const target = allMemories.find(m => m.id === c.memoryId);
    return {
      from: 'Recent memory',
      to: target?.content.slice(0, 60) ?? c.memoryId,
      relationship: c.relationship,
    };
  });

  // Flag low-confidence memories
  const flaggedReview = allMemories
    .filter(m => m.confidence < 0.7)
    .slice(0, 5)
    .map(m => ({
      id: m.id,
      content: m.content,
      reason: m.confidence < 0.5 ? 'Very low confidence — may be inaccurate' : 'Low confidence — verify with client',
    }));

  // Generate AI summary
  const summary = await generateSummary(tenantId, newMemories, connectionsMade, flaggedReview, stats, iqScore);

  return {
    reportDate: new Date().toISOString(),
    tenantId,
    generatedBy: 'donna',
    newMemories,
    connectionsMade,
    flaggedReview,
    stats,
    iqScore,
    summary,
  };
}

async function generateSummary(
  tenantId: string,
  newMemories: { content: string; type: string }[],
  connections: { relationship: string }[],
  flagged: { reason: string }[],
  stats: ReturnType<typeof getMemoryStats>,
  iqScore: IQScore,
): Promise<string> {
  try {
    const message = await client.messages.create({
      model: 'claude-sonnet-4-6-20250514',
      max_tokens: 256,
      system: `You are Donna, Chief AI Agent. Write a brief daily memory intelligence summary (2-3 sentences). Be concise and actionable. Use a professional but warm tone.`,
      messages: [{
        role: 'user',
        content: `Memory report for tenant ${tenantId}:
- ${newMemories.length} new memories stored
- ${connections.length} new connections discovered
- ${flagged.length} items flagged for review
- Total memories: ${stats.totalMemories}
- Confidence avg: ${stats.confidenceAvg}%
- IQ Score: ${iqScore.totalScore} (${iqScore.level}) — delta ${iqScore.delta > 0 ? '+' : ''}${iqScore.delta}
- New memory types: ${newMemories.map(m => m.type).join(', ')}`,
      }],
    });

    return message.content[0].type === 'text'
      ? message.content[0].text
      : 'Memory report generated successfully.';
  } catch {
    return `Stored ${newMemories.length} new memories. ${connections.length} connections discovered. ${flagged.length} items need review. IQ Score: ${iqScore.totalScore} (${iqScore.level}).`;
  }
}
